### ISSUE TITLE
Cannot generate example - messed up path?

### ISSUE THREAD

**Issue by py9mrg** [googleworkspace/md2googleslides#79]
When trying to run `md2gslides` on a cloned copy of the example slide, I get the following error:

```
C:\Data\GitHub\md2googleslides\examples>md2gslides example.md
Unable to generate slides: [Error: ENOENT: no such file or directory, open 'C:\C:\Data\GitHub\md2googleslides\examples\image_slide.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\C:\\Data\\GitHub\\md2googleslides\\examples\\image_slide.png'
}
```

image_slide.png is definitely in the correct folder so I presume the problem is the additional `C:\\` appended to the path - how do I prevent md2gslides from doing that? I tried specifying the full path in the example.md, but that doesn't help.

**Comment by wescpy** [comment]
This is the same bug as </issues/61>, so this should be marked as a duplicate of that one, which will also link to your useful comment above. By the way, what happens when you have plain ol' Markdown like: `![](image_slide.png)`?

**Comment by py9mrg** [comment]
Just had a trial - did it completely from scratch (deleted all old credentials etc) but got the following error:

![image](https://github.com/googleworkspace/md2googleslides/assets/12600721/041b771c-938a-4aeb-bbea-cae4a3e73ec8)

I *think* this might be related to a warning I got when generating the new project and credentials that it might take a few hours so will try again later.

**Comment by wescpy** [comment]
Thanks for the error msg. When you try again, can you outline your exact steps in more detail? I'm esp. curious about generating client credentials and what you do with them. Really try to follow [these steps](https://github.com/wescpy/md2googleslides#installation-and-usage) as verbatim as possible. Note that email addresses of the Cloud project must be the same as the user running the script. Don't mix work, test, or personal accounts.

I also may be missing a step or 2, so that's why I need to know. I'm going to link to a [intro to Workspace APIs tutorial](https://g.co/codelabs/gsuite-apis-intro). The tutorial is in Python (my main development tool), and that API used is the Drive API, but those aren't important here... getting authorization to use the Slides API is the same as the Drive API. The bulleted instructions should match all the steps outlined in module 7 _(Authorize API requests (user authorization)_ so make sure I didn't miss anything. In particular, you have to fill out an "OAuth consent screen" which aren't in my instructions (yet), so see if this page helps.

**Comment by py9mrg** [comment]
Strange, I have the same error. I tried to follow the instructions step by step as best I can, bearing in mind some things in Google have changed. I'll do them again now here so you can see. I am using my personal account only for this.

First, delete everything, all projects, credentials, everything, then, below are the current steps in the readme plus any comments from me.

- Create (or reuse) a developer project at https://console.developers.google.com
    - clicked `create_project` then modified the name to `md2gslides`, clicked `create`.
- Enable Google Slides API at API library page
    - searched for "slides", clicked `enable` (new md2gslides project selected in dropdown box at top left of window), took me to a new page (originally clicked `create credentials here` and followed through to the OAuth option but I assume this is the same but to be sure, this time I'm closing the window and using your link)
- Go to Credentials page and click "+ Create credentials" at the top - done
- Create "OAuth client ID" type of credentials. - done
- Choose type "Computer Application" and give it some name.
    - Chose the option "Desktop App" because there is no "Computer application" option and this seems most similar. Should I try "web application" instead?
    - Changed name to md2gslides, clicked create
    - Pop up window where I can download credentialXXX.json
- Download client ID/secret file and shorten the name to: client_id.json.
    - downloaded file to `C:\\Users\me\.md2googleslides\` and renamed to `client_id.json`.
- Move client_id.json (name has to be exact) to ~/.md2googleslides.

Then...

- Try to run the example (cloned repos, navigated to /examples and ran `md2gslides example.md`).
- Got the same error as above

I notice in Google's documentation you linked [this page](https://codelabs.developers.google.com/codelabs/gsuite-apis-intro/#6), which using your method doesn't present the section about `OAuth Consent` (the part where you click Internal or External. I have managed to do this by going to the relevant section (you can only click external and you can ignore nearly everything except the title and adding your email):

![image](https://github.com/googleworkspace/md2googleslides/assets/12600721/f12cf74a-6852-4db0-ae0e-4483a8f15f56)

BUT, on one of my tries it did present this screen to me automatically when I clicked `Create credentials` but it wasn't from your link, or the original one I tried, and I have fiddled so much I can't remember where exactly I clicked that to get it! I can delete everything AGAIN (!!) and see if I can force it, but the section in the image above should work as well.

Once I completed that I **still** have the error. BUT, if I go back to that section I notice there's a button `Publish`, which I have now clicked on and the page now shows:

![image](https://github.com/googleworkspace/md2googleslides/assets/12600721/a0d26c7d-38e7-4fe7-a58c-5ba46eacb406)

The error has now goes away. *Except* I now get this:

![image](https://github.com/googleworkspace/md2googleslides/assets/12600721/821d61b8-50a6-4d1f-a5a0-24b4ec5253b2)

I click advanced and then click the continue anyway button. It finally takes me to the consent screen and I can authorise. Phew!!

The only issue now is the path issue as per this issue. To answer the above question, `![](image_slide.png)` doesn't work (the example is already written that way). Further, I can't seem to make the hack work. The only place I can find the code is in `md2gslides\lib\images\probe.js.map` but changing it here as mentioned in the other issue doesn't help. Albeit, I realise I know zero about js/ts so it might not be that simple to do it post ts -> js compilation.

**Comment by wescpy** [comment]
You're **definitely** in a better place now. I think last time you clicked "external" app (instead of "internal") for the OAuth consent screen. I should add a bullet for that to the `README`.

Unfortunately I've got a medical procedure coming up and won't be able to look at the filepath issue until I get back. **However**, if you know anyone with Node.js skills who could do it, I'm happy to look at PRs. I just don't have the expertise to do it quickly. (This should be some sort-of _known_ problem in the Node.js ecosystem though... I'd be surprised if there isn't a solution out there already.)

**Comment by py9mrg** [comment]
Oh, I mean both times I selected external because the internal option is ghosted. I forget the message why, something to do with organisation maybe (I had to choose No Organisation for my project).

The key to get it working was to click the publish button in the OAuth consent section. Although I guess leaving it as testing and entering my own email in the authorised testers section towards the bottom might have helped. 

Don't worry about the other thing. I'll keep trying to work it out when I have the time and might ask the person who fixed it exactly what they did over on their issue. Hope the procedure goes well (and that it's nothing too serious).

If I have the chance, I'll try to do a PR to update the readme installation instructions but it might take some time as I'll have to delete everything and run through a few times to be confident exactly what steps are essential. I think there might need to be an "If your project has to be under No Organisation" section do ...

But I can't check what has to be done for the case where you can put your project under an organisation (which is presumably where "Internal" would work) because my company doesn't allow it. At least not with an arduous back and forth with IT that I expect they will rule out. 

Good luck, again.

**Comment by py9mrg** [comment]
Solved for Windows users with manual modification of installed code. See #61.
